print("ola, mundo!")
nome = input("Qual e seu nome")
idade = input("Quantos anos vc tem")
peso = input("quanto voce pesa")
cidade = input("Em que cidade voce nasceu")
print("--------------------------------")
print("        Ficha Pessoal")
print("--------------------------------")
print("o", nome, "tem", idade, "anos e ", peso, "kg. Nasceu na cidade do", cidade)